logreg/urls.py
from django.urls import path,include
from logreg import views

app_name='logreg'
urlpatterns = [
    path('index/',views.index,name='index'),
    path('login/',views.user_login,name='login'),
    path('signup/',views.register_user,name='signup'),
    
    path('special/',views.special,name='special'),
    path('logout/', views.log_request, name='logout'),
]

oppsdoor/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('staticmodule.urls')),
    path('logreg/',include('logreg.urls'),name='logreg1')
]

staticmodule/urls.py
from django.contrib import admin
from django.urls import path,include
from staticmodule import views

app_name='staticmodule'
urlpatterns = [
    path('',views.contactus,name='index'),
    path('mailsend/',views.MailSend.as_view(),name='mailsend'),
    path('mailnotsend/',views.MailNotSend.as_view(),name='mailnotsend'),
    path('logreg/',include('logreg.urls'),name='logreg1')
]

logreg/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    pro_pic=models.ImageField(upload_to='profile_pics',null=True,blank=True)
    portfolio_site = models.URLField(blank=True)
    def __str__(self):
        return self.user.username
    

staticmodule/models.py
from django.db import models

# Create your models here.

logreg/forms.py
from django import forms
from logreg.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password =forms.CharField(widget=forms.PasswordInput)
    class Meta():
        model=User
        fields=('username','password','email')
        
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields='__all__'
        

staticmodule/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
import floppyforms as forms

class ContactForm(forms.Form):

    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))
        super(ContactForm, self).__init__(*args, **kwargs)
        

logreg/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from logreg.forms import UserForm,UserProfileInfoForm
# Create your views here.
def index(request):
    return render(request,'logreg/index.html')@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def log_request(request):
    logout(request)
    return HttpResponse('You are logOut')
def register_user(request):
    registered=False
    if request.method== 'POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            profile=profile_form.save(commit=False)
            profile.user=user
            if 'profile_pic' in request.FILES:
                print('profile pic found')
                profile.profile_pic = request.FILES['pro_pic']
            profile.save()
            registered=True
        else:
            print(user_form.errors)
            print("_____________")
            print(profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
        user_details={'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered}
        return render(request,'logreg/index.html',context=user_details)

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active():
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'logreg/login.html', {})

staticmodule/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView ,FormView
from staticmodule.forms import ContactForm
from django.core.mail import send_mail
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect


# Create your views here.
class MailSend(TemplateView):
    template_name='staticmodule/mailsend.html'
# Create your views here.
class MailNotSend(TemplateView):
    template_name='staticmodule/mailsend.html'

def contactus(request):
#     return render(request, 'staticmodule/contactus.html')
    subject = request.POST.get('subject')
    message = request.POST.get('message')
    from_email = request.POST.get('email')
    if subject and message and from_email:
        try:
            send_mail(from_email, subject+" \n"+message,settings.EMAIL_HOST_USER , ['welcomemailalankrati@gmail.com'])
        except BadHeaderError:
            return HttpResponseRedirect('mailnotsend/')
        return HttpResponseRedirect('mailsend/')
    else:
        print(subject,message,from_email)
        # In reality we'd use a form class
        # to get proper validation errors.
        return render(request, 'staticmodule/index.html')

logreg/templates/logreg/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"></head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'dappx:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'dappx:user_login' %}">Login</a></li>
          {% endif %}</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

logreg/templates/logreg/index.html
{% block body_block %}<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Djungle !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>{% endblock %}

logreg/templates/logreg/login.html
{% extends 'dappx/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1><form method="post" action="{% url 'dappx:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username"><label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password"><input type="submit" name="" value="Login"></form></div>
  </div>
{% endblock %}

logreg/templates/logreg/registration.html
{% extends "dappx/base.html" %}
{% load staticfiles %}{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3><form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

staticmodule/templates/staticmodule/base.html
<!doctype html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="shortcut icon" href="{% static '/images/favicon.ico' %}" type="image/x-icon"/>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
		integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<!-- custome css -->
	<link rel="stylesheet" href="{% static 'css/master.css' %}">
	{% block title_block %}
	{% endblock %}
	
</head>

<body class=font_style>
	<!-- Navbar -->
	<nav class="navbar navbar-expand-lg navbackground p-1 sticky-top">
		<h1 class="mr-auto navbar-brand">
			<h1 class='nav_brand_color' style="font-size: 350%;">O</h1>pps<h1 class='nav_brand_color'>d</h1>oor
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse navbackground " id="navbarSupportedContent">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle navbackground" href="#" id="navbarDropdown" role="button"
							data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Dropdown
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="#">Action</a>
							<a class="dropdown-item" href="#">Another action</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="#">Something else here</a>
						</div>
					</li>
					<li class="nav-item active">
						<a class="nav-link navbackground" href="{% url 'staticmodule:index' %}">Home <span class="sr-only">(current)</span></a>
					</li>

					<li class="nav-item">
						<a class="nav-link navbackground" href="..">ourblog</a>
					</li>

				</ul>

			</div>
	</nav>
	<!-- Div 2 -->{% block body_block %}
	{% endblock %}
	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
		integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
		crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
		integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
		crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
		integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
		crossorigin="anonymous"></script>
</body>

</html>

staticmodule/templates/staticmodule/index.html
<!doctype html>

{% extends 'staticmodule/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<!-- title block -->
{% block title_block %}
<title>Oppsdoor</title>
{% endblock %}
<!-- bodyblock -->
{% block body_block %}
<div class="container-fluid ">
	<div id="one" class="container-fluid mt-2 mb-4">
		<div class="row">
			<div class="col-md-6 col-sm-6 mb-4">
				<div class="opd-ban-text">
					<h1 class="display-3 pb-2 mt-2 mb-2">What we provide </h1>
					<br>
					<p class=" pt-2 mt-2 mb-2">Orvador is a boutique digital marketing agency working with small and
						medium
						businesses to
						help them growth hack their target market. We work with data-driven organic and paid marketing
						strategies that are specifically designed for your business goals.
					</p><br><br>
					<a class="btn  btn-lg rounded-pill" href="#" role="button"
						style="background-color: #3ae8ad; color:black;">Learn more</a>
				</div>
			</div>
			<div class="col-md-6 col-sm-6 ">
				<img class=" image_master img-thumbnail " src="{% static '/images/image2.jpg' %}"
					alt="Oh shit Image is dead" style="border: 0px;">
			</div>
		</div>

	</div>
</div>
<div class="row ">
	<div class="col-md-4 col-sm-4">
		<hr style="background-color: silver; " width="10%" />
	</div>
	<div class="col-md-4 col-sm-4">
		<hr style="background-color: silver; " width="10%" />
	</div>
	<div class="col-md-4 col-sm-4">
		<hr style="background-color: silver; " width="10%" />
	</div>
</div>

<!-- div2 -->
<div class="container-fluid mb-2 pb-2 ">
	<div class="row ">

		<div class="font_style Text-Center p-3">
			<h4 class="display-4 text-dark p-1 font_style">Training Modules </h2>

		</div>

		<div class="row">
			<div class="col-md-3 col-sm-3 mb-4">
				<div class="card" style="width: 18rem;">
					<img class="card-img-top" src="{% static '/images/image2.jpg' %}" alt="zombie eat me">
					<div class="card-body">
						<p class="card-text">Some quick example text to build on the card title and make up the bulk of
							the
							card's content.</p>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-3 mb-4">
				<div class="card" style="width: 18rem;">
					<img class="card-img-top" src="{% static '/images/image2.jpg' %}" alt="devil steal my soul">
					<div class="card-body">
						<p class="card-text">Some quick example text to build on the card title and make up the bulk of
							the
							card's content.</p>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-3 mb-4">
				<div class="card" style="width: 18rem;">
					<img class="card-img-top" src="{% static '/images/image2.jpg' %}" alt="stack developer is lazy">
					<div class="card-body">
						<p class="card-text">Some quick example text to build on the card title and make up the bulk of
							the
							card's content.</p>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-3 mb-4">
				<div class="card" style="width: 18rem;">
					<img class="card-img-top" src="{% static '/images/image2.jpg' %}" alt="i love weed">
					<div class="card-body">
						<p class="card-text">Some quick example text to build on the card title and make up the bulk of
							the
							card's content.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- section 3 -->
<div class="container-fluid banner_2">
	<div class="row ">
		<div class="font_style Text-Center p-3 ">
			<h4 class="display-4 nav_brand_color p-1 ">Training methodology </h2>

		</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-sm-6 mb-4">
			<div class="opd-ban1-text">
				<h1 class="display-3 pb-2 mt-2 mb-2 text-light">What we provide </h1>
				<br>
				<p class=" pt-2 mt-2 mb-2">Orvador is a boutique digital marketing agency working with small and
					medium
					businesses to
					help them growth hack their target market. We work with data-driven organic and paid marketing
					strategies that are specifically designed for your business goals.
				</p><br><br>
				<a class="btn  btn-lg rounded-pill" href="#" role="button"
					style="background-color: #3ae8ad; color:black;">Learn more</a>
			</div>
		</div>
		<div class="col-md-6 col-sm-6 ">
			<img class=" image_master img-thumbnail " src="{% static '/images/image2.jpg' %}"
				alt="Oh shit Image is dead" style="border: 0px;">
		</div>
	</div>
	<div class="row ">
		<div class="col-md-4 col-sm-4">
			<hr style="background-color: rgb(0, 0, 0); " width="10%" />
		</div>
		<div class="col-md-4 col-sm-4">
			<hr style="background-color: rgb(0, 0, 0); " width="10%" />
		</div>
		<div class="col-md-4 col-sm-4">
			<hr style="background-color: rgb(0, 0, 0); " width="10%" />
		</div>
	</div>
</div>
<!-- section 4 -->
<div class="container-fluid mb-2 pb-2 ">
	<div class="row ">

		<div class="font_style Text-Center p-3">
			<h4 class="display-4 text-dark p-1 font_style">Our Team </h2>

		</div>

		<div class="row">
			<div class="col-md-3 col-sm-3 mb-4">
				<div class="card" style="width: 18rem;">
					<img class="card-img-top rounded-circle" src="{% static '/images/image2.jpg' %}"
						alt="stack developer is lazy">

					<div class="card-body">
						<p class="card-text">Some quick example text to build on the card title and make up the bulk of
							the
							card's content.</p>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-3 mb-4">
				<div class="card" style="width: 18rem;">
					<img class="card-img-top rounded-circle" src="{% static '/images/image2.jpg' %}"
						alt="stack developer is lazy">

					<div class="card-body">
						<p class="card-text">Some quick example text to build on the card title and make up the bulk of
							the
							card's content.</p>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-3 mb-4">
				<div class="card" style="width: 18rem;">
					<img class="card-img-top rounded-circle" src="{% static '/images/image2.jpg' %}"
						alt="stack developer is lazy">
					<div class="card-body">
						<p class="card-text">Some quick example text to build on the card title and make up the bulk of
							the
							card's content.</p>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-3 mb-4">
				<div class="card" style="width: 18rem;">
					<img class="card-img-top rounded-circle" src="{% static '/images/image2.jpg' %}"
						alt="stack developer is lazy">

					<div class="card-body">
						<p class="card-text">Some quick example text to build on the card title and make up the bulk of
							the
							card's content.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- section contact us -->
<div class="container-fluid banner_2" id="contact us">

	<div class="row banner_2 ">

		<br><br>

	</div>
	<div class="row bg-light">

		<div class="font_style Text-Center  p-1">
			<h4 class=" text-dark p-1 font_style">Contact us</h2>

		</div>

	</div>
	<div class="row banner_2">

		<div class="container_form mx-auto pt-3 pb-3">
			<form class="contact_form  " method="POST">
				{% csrf_token %}

				<div class="form-row contact_form">
					<div class="form-group col-md-6">
						<label for="name">
							<h3 class="text-light">Subject*</h3>
						</label>
						<input type="text" class="form-control" id="name" name="subject"
							placeholder="Enter the Subject here">
					</div>
					<div class="form-group col-md-6">
						<label for="email">
							<h3 class="text-light">Email*</h3>
						</label>
						<input type="email" class="form-control" id="email" name="email" placeholder="Your Email ">
					</div>
				</div>
				<div class="form-group">
					<label for="message">
						<h3 class="text-light">Message*</h3>
					</label>
					<textarea class="form-control" id="message" rows="5" name="message"
						placeholder="Your Message"></textarea>
				</div>
<p><small class="text-light">All * fields are required and we will not published your mail Id</small></p>
				<button type="submit" class="btn" style="background-color: #3ae8ad; color:White;">Send Mail</button>
			</form>
			
		</div>

	</div>
</div>

{% endblock %}

staticmodule/templates/staticmodule/mailnotsend.html
<!doctype html>
{% extends 'staticmodule/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}
<title>Main not Send</title>
{% endblock %}
{% block body_block %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Something happen bad  </h1>
    <p class="lead">Please check the details and try again</p>
  </div>
</div>
{% endblock %}

staticmodule/templates/staticmodule/mailsend.html
<!doctype html>
{% extends 'staticmodule/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}
<title>Main Send</title>
{% endblock %}
{% block body_block %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Email Send </h1>
    <p class="lead">Thank to showing interest ,we will contant you soon</p>
  </div>
</div>
{% endblock %}